import { waitForDataRoute } from "./fixtures/routeReady";
import { refetchGate, measureFastRefetch } from './fixtures/refetch';
import { test, expect, type Page } from '@playwright/test';
import { mockDirectory } from './fixtures/directory';
import { assertNoDataSpinner, captureFixedOverlay, checkRenderedContrast, checkShimmerPixels } from './design-pixels';
import fs from 'node:fs';
const url='/teacher/attendance/records';
async function fixture(page:Page,dark:boolean,count=3,long=false){
 await page.clock.setFixedTime(new Date('2026-10-09T04:00:00Z'));const context=await mockDirectory(page,'TEACHER',dark);let releaseSections!:()=>void,releaseAttendance!:()=>void;const sectionGate=new Promise<void>(r=>{releaseSections=r;}),dataGate=new Promise<void>(r=>{releaseAttendance=r;});let failed='';const refetch=refetchGate();const saves:unknown[]=[];
 await page.route('**/api/teacherAttendance/advisory-sections',async route=>{await sectionGate;await route.fulfill({status:failed==='sections'?500:200,json:failed==='sections'?{}:[{classId:'1',sectionId:'1',sectionName:long?'Maroon Primary School Section '.repeat(3):'Maroon',gradeLevel:'Grade 1',roster:Array.from({length:count},(_,i)=>({id:String(i+1),name:long?'Maria Alexandra Isabella Delos Santos '.repeat(3):`Ana Cruz ${i+1}`,gender:i%2?'F':'M'})),terms:[{id:'1',termNumber:1,label:'Term 1',startDate:'2026-10-01',endDate:'2026-10-31',isActive:true},{id:'2',termNumber:2,label:'Term 2',startDate:'2026-11-01',endDate:'2026-11-30',isActive:false}]}]});});
 await page.route('**/api/teacherAttendance/1?*',async route=>{if(route.request().method()==='POST'){saves.push(route.request().postDataJSON());await route.fulfill({json:{success:true}});return;}await dataGate;await refetch.wait();await route.fulfill({status:failed==='attendance'?500:200,json:failed==='attendance'?{}:{data:Object.fromEntries(Array.from({length:count},(_,i)=>[String(i+1),{'2026-10-08':i%2?'A':'P','2026-10-09':'P'}]))}});});
 await page.route('**/api/teacherAttendance/1',async route=>{saves.push(route.request().postDataJSON());await route.fulfill({json:{success:true}});});
 return {sections:()=>{context();releaseSections();},data:()=>releaseAttendance(),all:()=>{context();releaseSections();releaseAttendance();},fail:(kind:string)=>{failed=kind;},recover:()=>{failed='';},hold:refetch.hold,releaseRefetch:refetch.release,saves};
}
for(const width of [375,1280])for(const dark of [false,true])test(`attendance records ${width} ${dark?'dark':'light'} keeps date headers and view controls real`,async({page})=>{
 await page.setViewportSize({width,height:1100});const request=await fixture(page,dark);await page.goto(url);await waitForDataRoute(page);await expect(page.getByRole('heading',{name:'Attendance Records',exact:true}).first()).toBeVisible();await expect(page.getByRole('button',{name:'Month',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Summary',exact:true})).toBeVisible();await expect(page.getByRole('columnheader',{name:'Student',exact:true})).toBeVisible();await expect(page.getByText('October 2026',{exact:true})).toBeVisible();request.sections();await expect(page.locator('[data-sk-region="attendance-records-roster"]')).toHaveAttribute('data-sk-phase','settled');await expect(page.getByText('Ana Cruz 1',{exact:true})).toBeVisible();await expect(page.locator('[data-sk-region="attendance-records-table"]')).toHaveCount(1);await expect(page.locator('[data-sk-region="attendance-records-table"]')).toHaveAttribute('data-sk-phase','revealed');await assertNoDataSpinner(page);
 const verify=await captureFixedOverlay(page,`attendance-record-cells-${width}-${dark?'dark':'light'}`,[':nth-match([data-sk-region="attendance-present-cell"], 1)',':nth-match([data-sk-region="attendance-status-cell"], 1)']);const headers=await page.locator('thead th').evaluateAll(elements=>elements.map(element=>{const box=element.getBoundingClientRect();return {x:box.x,width:box.width};}));const prefix=`loading-screenshots/attendance-records-${width}-${dark?'dark':'light'}`;fs.mkdirSync('loading-screenshots',{recursive:true});await page.screenshot({path:prefix+'-skeleton.png',fullPage:true});request.data();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.locator('[data-sk-region="attendance-record-row"]')).toHaveCount(3);const loaded=await page.locator('thead th').evaluateAll(elements=>elements.map(element=>{const box=element.getBoundingClientRect();return {x:box.x,width:box.width};}));expect(loaded).toHaveLength(headers.length);headers.forEach((box,i)=>{expect(Math.abs(box.x-loaded[i].x)).toBeLessThanOrEqual(1);expect(Math.abs(box.width-loaded[i].width)).toBeLessThanOrEqual(1);});await verify();await page.screenshot({path:prefix+'-loaded.png',fullPage:true});
});
for(const width of [375,1280])for(const dark of [false,true])test(`attendance summary ${width} ${dark?'dark':'light'} keeps labels and calendar dates real`,async({page})=>{
 await page.setViewportSize({width,height:1100});const request=await fixture(page,dark);await page.goto(url);await waitForDataRoute(page);request.sections();await expect(page.locator('[data-sk-region="attendance-records-roster"]')).toHaveAttribute('data-sk-phase','settled');await page.getByRole('button',{name:'Summary',exact:true}).click();await expect(page.getByRole('heading',{name:'Monthly Summary',exact:true})).toBeVisible();await expect(page.getByText('Absences this month',{exact:true})).toBeVisible();await expect(page.getByText('Sun',{exact:true})).toBeVisible();await expect(page.getByText('School days',{exact:true})).toBeVisible();await expect(page.locator('[data-sk-region="attendance-month-summary"]')).toHaveAttribute('data-sk-phase','revealed');await assertNoDataSpinner(page);const verify=await captureFixedOverlay(page,`attendance-summary-${width}-${dark?'dark':'light'}`,['School days','Present','Absent','Late / Excused'].map(label=>`[data-sk-region="attendance-summary-value-${label}"]`));const prefix=`loading-screenshots/attendance-summary-${width}-${dark?'dark':'light'}`;await page.screenshot({path:prefix+'-skeleton.png',fullPage:true});request.data();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.getByText('Ana Cruz 2',{exact:true})).toBeVisible();await verify();await page.screenshot({path:prefix+'-loaded.png',fullPage:true});
});
for(const count of [0,1,9])test(`attendance records preserves ${count} actual roster rows`,async({page})=>{const request=await fixture(page,false,count,count===9);await page.goto(url);await waitForDataRoute(page);request.all();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.locator('[data-sk-region="attendance-record-row"]')).toHaveCount(count);if(!count)await expect(page.getByText('No students enrolled yet.',{exact:true})).toBeVisible();});
for(const view of ['Month','Summary'])test(`attendance ${view} request error clears all shapes and retries`,async({page})=>{const request=await fixture(page,false);request.fail('attendance');await page.goto(url);await waitForDataRoute(page);request.sections();if(view==='Summary')await page.getByRole('button',{name:'Summary',exact:true}).click();request.data();await expect(page.getByRole('alert')).toBeVisible();await expect(page.locator('[data-sk-primitive]')).toHaveCount(0);request.recover();await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);});
test('attendance advisory error has a real retry',async({page})=>{const request=await fixture(page,false);request.fail('sections');await page.goto(url);await waitForDataRoute(page);request.all();await expect(page.getByRole('alert')).toBeVisible();await expect(page.locator('[data-sk-primitive]')).toHaveCount(0);request.recover();await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByText('Ana Cruz 1',{exact:true})).toBeVisible();});
for(const slow of [false,true])test(`attendance term ${slow?'slow':'fast'} refetch preserves rows`,async({page})=>{const request=await fixture(page,false);await page.goto(url);await waitForDataRoute(page);request.all();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);const region=page.locator('[data-sk-region="attendance-records-table"]');await expect(region).toHaveAttribute('data-sk-phase','settled');await region.evaluate(element=>{const phases:string[]=[];(window as unknown as {attendancePhases:string[]}).attendancePhases=phases;new MutationObserver(()=>phases.push(element.getAttribute('data-sk-phase')??'')).observe(element,{attributes:true,attributeFilter:['data-sk-phase']});});const verifyFast=!slow?await measureFastRefetch(page,'teacherAttendance/1?'):undefined;request.hold(!slow);await page.getByRole('combobox',{name:'Term',exact:true}).selectOption('2');if(slow){await expect(region).toHaveAttribute('data-sk-phase','dimmed');await expect(region.locator('[data-sk-stale]')).toHaveCSS('opacity','0.6');await expect(region.getByText('Ana Cruz 1',{exact:true})).toBeVisible();await expect(region).toHaveAttribute('data-sk-phase','revealed');request.releaseRefetch();}await verifyFast?.();await expect(region).toHaveAttribute('data-sk-phase','settled');if(!slow){const phases=await page.evaluate(()=>(window as unknown as {attendancePhases:string[]}).attendancePhases);expect(phases).not.toContain('dimmed');expect(phases).not.toContain('revealed');}await assertNoDataSpinner(page);});
test('attendance marking keeps the original cycle and save payload',async({page})=>{const request=await fixture(page,false);await page.goto(url);await waitForDataRoute(page);request.all();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);const row=page.locator('[data-sk-region="attendance-record-row"]').first();await row.locator('button[title*="mark today"]').click();await expect.poll(()=>request.saves.length).toBe(1);expect(request.saves[0]).toEqual({studentId:'1',date:'2026-10-09',status:'A',term:'1'});});
for(const dark of [false,true])test(`attendance ${dark?'dark':'light'} summary numeric surfaces retain contrast`,async({page})=>{const request=await fixture(page,dark);await page.goto(url);await waitForDataRoute(page);request.sections();await page.getByRole('button',{name:'Summary',exact:true}).click();await expect(page.locator('[data-sk-region="attendance-month-summary"]')).toHaveAttribute('data-sk-phase','revealed');const shape=page.locator('[data-sk-region="attendance-summary-value-School days"] [data-sk-primitive]');await checkRenderedContrast(shape,`attendance-summary-${dark?'dark':'light'}`);await checkShimmerPixels(shape,`attendance-summary-${dark?'dark':'light'}`);});


test('attendance native fixed columns do not vary across roster names or counts',async({page})=>{const widths:number[][]=[];for(const long of [false,true]){const request=await fixture(page,false,long?9:1,long);await page.goto(url);await waitForDataRoute(page);request.all();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);const table=page.locator('[data-sk-region="attendance-native-table"]');await expect(table.locator('[data-sk-auto-columns]')).toHaveCount(0);widths.push(await table.locator('thead th').evaluateAll(elements=>elements.map(element=>element.getBoundingClientRect().width)));await page.unroute('**/api/**');await page.unroute('**/api/teacherAttendance/advisory-sections');await page.unroute('**/api/teacherAttendance/1?*');await page.unroute('**/api/teacherAttendance/1');}expect(widths[0]).toHaveLength(widths[1].length);widths[0].forEach((width,i)=>expect(Math.abs(width-widths[1][i])).toBeLessThanOrEqual(1));});


