import { waitForDataRoute } from "./fixtures/routeReady";
import { test, expect, type Page } from '@playwright/test';
import { mockDirectory } from './fixtures/directory';
import { assertNoDataSpinner, captureFixedOverlay, checkRenderedContrast, checkShimmerPixels } from './design-pixels';
import fs from 'node:fs';
async function fixture(page:Page,dark:boolean,count=1,missing=false){
 const context=await mockDirectory(page,'ADMIN',dark);let finish!:()=>void;const gate=new Promise<void>(r=>{finish=r;});let failure='';
 await page.route('**/api/classes/**',async route=>{await gate;const path=new URL(route.request().url()).pathname;const fail=failure&&(failure==='record'?path==='/api/classes/':path.includes(failure));if(fail){await route.fulfill({status:500,json:{message:'Class data unavailable'}});return;}
 let data:unknown=[];if(path==='/api/classes/')data=missing?[]:[{id:1,gradeLevelId:1,gradeLevel:'Grade 1',sectionId:1,section:'Maroon',room:'101',adviserId:1,adviserName:'Ana Cruz',studentCount:3,schedule:Array.from({length:count},(_,index)=>({id:index+1,subject:'Mathematics',teacherId:1,teacherName:'Ana Cruz',startTime:'07:30',endTime:'08:30',days:['Monday']}))}];else if(path.endsWith('gradeLevels'))data=[{id:1,grade_level:'Grade 1'}];else if(path.endsWith('teacher/all'))data=[{id:1,first_name:'Ana',last_name:'Cruz'}];else if(path.endsWith('sections'))data=[{id:1,section_name:'Maroon'}];else if(path.includes('getSubByGrade'))data=[{id:1,subject_name:'Mathematics'}];await route.fulfill({json:{success:true,data}});
 });return Object.assign(()=>{context();finish();},{fail:(kind:string)=>{failure=kind;},recover:()=>{failure='';}});
}
for(const width of [375,1280])for(const dark of [false,true])test(`class edit ${width} ${dark?'dark':'light'} keeps original fields and schedule controls`,async({page})=>{
 await page.setViewportSize({width,height:1100});const release=await fixture(page,dark);await page.goto('/admin/classes/1/edit');await waitForDataRoute(page);await expect(page.getByRole('heading',{name:'Edit Class',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Add Period',exact:true})).toBeVisible();await expect(page.locator('[data-sk-region="class-form-room"]')).toHaveAttribute('data-sk-phase','revealed');await assertNoDataSpinner(page);await expect(page.getByText(/No class found/)).toHaveCount(0);
 const verify=await captureFixedOverlay(page,`admin-class-edit-${width}-${dark?'dark':'light'}`,['gradeLevelId','section','room'].map(field=>`[data-sk-region="class-form-${field}"]`));fs.mkdirSync('loading-screenshots',{recursive:true});const prefix=`loading-screenshots/admin-class-edit-${width}-${dark?'dark':'light'}`;await page.screenshot({path:prefix+'-skeleton.png',fullPage:true});release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.getByPlaceholder('NEL 101')).toHaveValue('101');await expect(page.locator('[data-sk-region="class-form-period"]')).toHaveCount(1);await verify();await page.screenshot({path:prefix+'-loaded.png',fullPage:true});
});
for(const count of [0,1,8])test(`class edit retains ${count} actual schedule periods`,async({page})=>{const release=await fixture(page,false,count);await page.goto('/admin/classes/1/edit');await waitForDataRoute(page);await expect(page.getByRole('heading',{name:'Edit Class',exact:true})).toBeVisible();release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.locator('[data-sk-region="class-form-period"]')).toHaveCount(count);if(!count)await expect(page.getByText('No periods added yet.',{exact:true})).toBeVisible();});
for(const kind of ['record','gradeLevels','teacher/all','sections','getSubByGrade'])test(`class form retries ${kind} failure`,async({page})=>{const release=await fixture(page,false);release.fail(kind);await page.goto('/admin/classes/1/edit');await waitForDataRoute(page);release();await expect(page.getByRole('alert')).toBeVisible();await expect(page.locator('[data-sk-primitive]')).toHaveCount(0);release.recover();await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.getByPlaceholder('NEL 101')).toHaveValue('101');});
for(const width of [375,1280])for(const dark of [false,true])test(`class new ${width} ${dark?'dark':'light'} preserves known empty values`,async({page})=>{await page.setViewportSize({width,height:1100});const release=await fixture(page,dark);await page.goto('/admin/classes/new');await waitForDataRoute(page);await expect(page.getByRole('heading',{name:'Add New Class',exact:true})).toBeVisible();await assertNoDataSpinner(page);await expect(page.locator('main [data-sk-primitive]')).toHaveCount(0);await page.getByPlaceholder('NEL 101').fill('NEL 202');fs.mkdirSync('loading-screenshots',{recursive:true});const prefix=`loading-screenshots/admin-class-new-${width}-${dark?'dark':'light'}`;await page.screenshot({path:prefix+'-skeleton.png',fullPage:true});release();await expect(page.getByRole('combobox',{name:'Class adviser',exact:true})).toBeEnabled();await expect(page.getByPlaceholder('NEL 101')).toHaveValue('NEL 202');await page.screenshot({path:prefix+'-loaded.png',fullPage:true});});
test('class edit saves the original mapped schedule payload',async({page})=>{const release=await fixture(page,false);let payload:unknown;await page.route('**/api/classes/updateClass/1',async route=>{payload=route.request().postDataJSON();await route.fulfill({json:{success:true}});});await page.goto('/admin/classes/1/edit');await waitForDataRoute(page);release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await page.getByPlaceholder('NEL 101').fill('202');await page.getByRole('button',{name:'Save Changes',exact:true}).click();await expect.poll(()=>payload).toEqual({gradeLevel:1,section:'Maroon',room:'202',adviserId:1,schedule:[{subject:'Mathematics',teacherId:1,startTime:'07:30',endTime:'08:30',days:['Monday']}]});});
for(const dark of [false,true])test(`class form ${dark?'dark':'light'} input surface pixels`,async({page})=>{await fixture(page,dark);await page.goto('/admin/classes/1/edit');await waitForDataRoute(page);await expect(page.locator('[data-sk-region="class-form-room"]')).toHaveAttribute('data-sk-phase','revealed');const shape=page.locator('[data-sk-region="class-form-room"] [data-sk-primitive]');await checkRenderedContrast(shape,`class-form-${dark?'dark':'light'}`);await checkShimmerPixels(shape,`class-form-${dark?'dark':'light'}`);});
for(const dark of [false,true])test(`class adviser ${dark?'dark':'light'} disabled control surface pixels`,async({page})=>{await fixture(page,dark);await page.goto('/admin/classes/1/edit');await waitForDataRoute(page);await expect(page.locator('[data-sk-region="class-form-room"]')).toHaveAttribute('data-sk-phase','revealed');const shape=page.locator('[data-sk-region="class-adviser-value"] [data-sk-primitive]').first().or(page.getByRole('combobox',{name:'Class adviser',exact:true}).locator('[data-sk-primitive]')).first();await checkRenderedContrast(shape,`class-adviser-${dark?'dark':'light'}`);await checkShimmerPixels(shape,`class-adviser-${dark?'dark':'light'}`);});
test('class form keeps the known Updating prefix real before record data arrives',async({page})=>{await fixture(page,false);await page.goto('/admin/classes/1/edit');await waitForDataRoute(page);await expect(page.getByText('Updating',{exact:true})).toBeVisible();});
