import { waitForDataRoute } from "./fixtures/routeReady";
import { refetchGate, measureFastRefetch } from './fixtures/refetch';
import { test, expect, type Page } from '@playwright/test';
import { mockDirectory } from './fixtures/directory';
import { assertNoDataSpinner, captureFixedOverlay, checkRenderedContrast, checkShimmerPixels } from './design-pixels';
import fs from 'node:fs';
const url='/teacher/holistic/domain-trends';
async function fixture(page:Page,dark:boolean,weeks=3,subjectCount=2,long=false,advisories=1){
 const context=await mockDirectory(page,'TEACHER',dark);let finish!:()=>void;const gate=new Promise<void>(r=>{finish=r;});let failed='';const refetch=refetchGate();
 const points=Array.from({length:weeks},(_,i)=>({weekStartDate:`2026-09-${String(1+i*3).padStart(2,'0')}`,cognitive:3.5+i*.1,emotional:3.8,behavioral:2.6,social:4.2}));
 await page.route('**/api/teacherAttendance/advisory-sections',async route=>{await gate;await route.fulfill({status:failed==='advisories'?500:200,json:failed==='advisories'?{message:'Advisories unavailable'}:Array.from({length:advisories},(_,i)=>({classId:String(i+1),sectionId:String(i+1),sectionName:long?'Maroon Primary School '.repeat(3):i?'White':'Maroon',gradeLevel:'Grade 1',roster:[],terms:[]}))});});
 await page.route('**/api/gradingPeriods',async route=>{await gate;await route.fulfill({status:failed==='terms'?500:200,json:failed==='terms'?{success:false,message:'Terms unavailable'}:{success:true,data:[1,2].map(id=>({id:String(id),schoolYearId:'1',termNumber:id,termLabel:`Term ${id}`,startDate:'2026-09-01',endDate:'2026-12-01',isActive:id===1}))}});});
 await page.route('**/api/teacherHolistic/domain-trends?*',async route=>{await gate;await refetch.wait();await route.fulfill({status:failed==='trends'?500:200,json:failed==='trends'?{success:false,message:'Trends unavailable'}:{success:true,data:{sections:Array.from({length:advisories},(_,i)=>({classId:String(i+1),sectionId:String(i+1),sectionName:'Maroon',gradeLevel:'Grade 1',subjects:Array.from({length:subjectCount},(_,index)=>({subjectSectionId:String(index+1),subjectName:long?`Mathematics and quantitative reasoning for elementary learners ${index}`:index?'Reading':'Mathematics',studentCount:3,weeks:points})),overallWeeks:points}))}}});});
 return Object.assign(()=>{context();finish();},{fail:(kind:string)=>{failed=kind;},recover:()=>{failed='';},hold:refetch.hold,releaseTrends:refetch.release});
}
for(const width of [375,1280])for(const dark of [false,true])test(`domain trends ${width} ${dark?'dark':'light'} keeps domains and chart shell real`,async({page})=>{
 await page.setViewportSize({width,height:1100});const release=await fixture(page,dark);await page.goto(url);await waitForDataRoute(page);await expect(page.getByRole('heading',{name:'Domain Trends',exact:true})).toBeVisible();await expect(page.getByText('Weekly Progression',{exact:true})).toBeVisible();await expect(page.getByText('What the data means',{exact:true})).toBeVisible();await expect(page.getByText('Cognitive',{exact:true}).first()).toBeVisible();await expect(page.locator('[data-sk-region="domain-trends-body"]')).toHaveAttribute('data-sk-phase','revealed');await assertNoDataSpinner(page);
 const verify=await captureFixedOverlay(page,`domain-trends-${width}-${dark?'dark':'light'}`,['cognitive','emotional','behavioral','social'].map(key=>`[data-sk-region="domain-trend-score-${key}"]`));fs.mkdirSync('loading-screenshots',{recursive:true});const prefix=`loading-screenshots/domain-trends-${width}-${dark?'dark':'light'}`;await page.screenshot({path:prefix+'-skeleton.png',fullPage:true});release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.getByRole('button',{name:'Mathematics',exact:true})).toBeVisible();await verify();await page.screenshot({path:prefix+'-loaded.png',fullPage:true});await expect(page.locator('[data-sk-primitive], [role=status]')).toHaveCount(0);
});
for(const count of [0,1,9])test(`domain trends preserves ${count} actual weeks and empty state`,async({page})=>{const release=await fixture(page,false,count,count===9?9:2,count===9);await page.goto(url);await waitForDataRoute(page);release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);if(count)await expect(page.getByText(`Based on ${count} week${count===1?'':'s'} of ratings recorded so far in this term.`,{exact:true})).toBeVisible();else await expect(page.getByText('No weekly records yet for this term.',{exact:true})).toBeVisible();});
for(const kind of ['terms','advisories','trends'])test(`domain trends retries ${kind} failure and clears placeholders`,async({page})=>{const release=await fixture(page,false);release.fail(kind);await page.goto(url);await waitForDataRoute(page);release();await expect(page.getByRole('alert')).toBeVisible();await expect(page.locator('[data-sk-primitive]')).toHaveCount(0);release.recover();await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.getByText('Based on 3 weeks of ratings recorded so far in this term.',{exact:true})).toBeVisible();});
for(const dark of [false,true])test(`domain trends ${dark?'dark':'light'} neutral score and colored composite contrast`,async({page})=>{await fixture(page,dark);await page.goto(url);await waitForDataRoute(page);await expect(page.locator('[data-sk-region="domain-trends-body"]')).toHaveAttribute('data-sk-phase','revealed');for(const name of ['domain-trend-score-cognitive','domain-trend-composite']){const shape=page.locator(`[data-sk-region="${name}"] [data-sk-primitive]`).first();await checkRenderedContrast(shape,`${name}-${dark?'dark':'light'}`);await checkShimmerPixels(shape,`${name}-${dark?'dark':'light'}`);}});
test('domain chart placeholder preserves the line-chart silhouette',async({page})=>{const release=await fixture(page,false);await page.goto(url);await waitForDataRoute(page);const plot=page.locator('[data-sk-chart="lines"]');await expect(plot.locator('[data-sk-line]')).toHaveCount(4);expect(await plot.locator('[data-sk-line]').first().evaluate(element=>getComputedStyle(element).clipPath)).not.toBe('none');release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(plot.locator('.recharts-line-curve')).toHaveCount(4);});
test('domain subject selection and legend toggles keep their existing behavior',async({page})=>{const release=await fixture(page,false);await page.goto(url);await waitForDataRoute(page);release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await page.getByRole('button',{name:'Mathematics',exact:true}).click();await expect(page.getByText('Mathematics snapshot',{exact:true})).toBeVisible();const legend=page.getByRole('button',{name:'Cognitive',exact:true});await legend.click();await expect(page.getByRole('button',{name:'Show on chart',exact:true})).toHaveCount(1);await legend.click();await expect(page.getByRole('button',{name:'Show on chart',exact:true})).toHaveCount(0);});
test('domain trends no-advisory result settles to its existing empty state',async({page})=>{const release=await fixture(page,false,3,2,false,0);await page.goto(url);await waitForDataRoute(page);release();await expect(page.getByText('No advisory class assigned to you.',{exact:true})).toBeVisible();await expect(page.locator('[data-sk-primitive], [role=status]')).toHaveCount(0);});

for(const slow of [false,true])test(`domain trends ${slow?'slow':'fast'} term refetch preserves previous data`,async({page})=>{
 const release=await fixture(page,false);await page.goto(url);await waitForDataRoute(page);release();const region=page.locator('[data-sk-region="domain-trends-body"]');await expect(region).toHaveAttribute('data-sk-phase','settled');const heading=await page.getByRole('heading',{name:'Domain Trends',exact:true}).boundingBox();
 await region.evaluate(element=>{const phases:string[]=[];(window as unknown as {domainPhases:string[]}).domainPhases=phases;new MutationObserver(()=>phases.push(element.getAttribute('data-sk-phase')??'')).observe(element,{attributes:true,attributeFilter:['data-sk-phase']});});
 const verifyFast=!slow?await measureFastRefetch(page,'teacherHolistic/domain-trends'):undefined;release.hold(!slow);await page.getByRole('combobox',{name:'Select term',exact:true}).selectOption('2');if(slow){await expect(region).toHaveAttribute('data-sk-phase','dimmed');await expect(region.locator('[data-sk-stale]')).toHaveCSS('opacity','0.6');await expect(region.getByText('Based on 3 weeks of ratings recorded so far in this term.',{exact:true})).toBeVisible();await expect(region).toHaveAttribute('data-sk-phase','revealed');release.releaseTrends();}
 await verifyFast?.();await expect(region).toHaveAttribute('data-sk-phase','settled');expect(await page.getByRole('heading',{name:'Domain Trends',exact:true}).boundingBox()).toEqual(heading);const phases=await page.evaluate(()=>(window as unknown as {domainPhases:string[]}).domainPhases);if(!slow){expect(phases).toContain('waiting');expect(phases).not.toContain('dimmed');expect(phases).not.toContain('revealed');}await assertNoDataSpinner(page);
});
for(const dark of [false,true])test(`domain trends ${dark?'dark':'light'} line shimmer retains its entire silhouette`,async({page})=>{await fixture(page,dark);await page.goto(url);await waitForDataRoute(page);await expect(page.locator('[data-sk-region="domain-trends-body"]')).toHaveAttribute('data-sk-phase','revealed');await page.locator('[data-sk-line]').evaluateAll(elements => { for (const element of elements) for (const animation of element.getAnimations({subtree:true})) animation.pause(); });await checkShimmerPixels(page.locator('[data-sk-line]').first(),`domain-trend-line-${dark?'dark':'light'}`);});
for(const count of [1,2,9])test(`domain trends ${count} subject tabs preserve native wrapping`,async({page})=>{await page.setViewportSize({width:375,height:1100});const release=await fixture(page,false,3,count,count===9,2);await page.goto(url);await waitForDataRoute(page);const tabs=page.locator('[data-sk-region="domain-trend-subject-tabs"]');await expect(tabs).toHaveAttribute('data-sk-phase','waiting');const initial=await tabs.boundingBox();await expect(tabs).toHaveAttribute('data-sk-phase','revealed');expect(await tabs.boundingBox()).toEqual(initial);const before=await page.getByRole('heading',{name:'Domain Trends',exact:true}).boundingBox();release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.locator('[data-sk-region="domain-trend-subject"]')).toHaveCount(count);expect(await page.getByRole('heading',{name:'Domain Trends',exact:true}).boundingBox()).toEqual(before);if(count===9)expect((await tabs.boundingBox())!.height).toBeGreaterThan(initial!.height);});

