import { waitForDataRoute } from "./fixtures/routeReady";
import {test,expect,type Page} from '@playwright/test';
import {mockDirectory} from './fixtures/directory';
import {assertNoDataSpinner,captureFixedOverlay,checkRenderedContrast,checkShimmerPixels} from './design-pixels';
import fs from 'node:fs';
const url='/teacher/holistic/1?term=1';
async function fixture(page:Page,dark:boolean,count=2,long=false,evaluations=3){const context=await mockDirectory(page,'TEACHER',dark);let finish!:()=>void;const gate=new Promise<void>(r=>{finish=r;});let failed='';const domains={cognitive:evaluations?3.9:null,emotional:evaluations?3.4:null,social:evaluations?4.3:null,behavioral:evaluations?2.7:null};
 await page.route('**/api/student/allStudents',async route=>{await gate;await route.fulfill({status:failed==='student'?500:200,json:failed==='student'?{message:'Student unavailable'}:{data:[{id:1,grade_level_id:1,section_id:1,student_number:'2026-01',learner_reference_number:'123456789001',first_name:long?'Maria Alexandra Isabella '.repeat(8):'Ana',last_name:'Cruz',middle_name:'',gender:'Female',grade_level_name:'Grade 1',section_name:'Maroon'}]}});});
 await page.route('**/api/gradingPeriods',async route=>{await gate;await route.fulfill({status:failed==='terms'?500:200,json:failed==='terms'?{success:false,message:'Terms unavailable'}:{success:true,data:[{id:'1',termNumber:1,termLabel:'Term 1',isActive:true}]}});});
 await page.route('**/api/teacherHolistic/profile/1?*',async route=>{await gate;await route.fulfill({status:failed==='profile'?500:200,json:failed==='profile'?{success:false,message:'Profile unavailable'}:{success:true,data:{studentId:'1',studentName:long?'Maria Alexandra Isabella '.repeat(8)+'Cruz':'Ana Cruz',isAdvisory:true,overall:{domainAverages:domains,evaluationCount:evaluations,lastEvaluation:evaluations?'2026-10-09':null},highestRiskLevel:'NONE',subjects:Array.from({length:count},(_,i)=>({subjectSectionId:String(i+1),subjectName:long?'Mathematics and quantitative reasoning '.repeat(3):i?'Reading':'Mathematics',domainAverages:domains,evaluationCount:evaluations,lastEvaluation:evaluations?'2026-10-09':null,riskLevel:'NONE',risks:[],recommendations:[{domain:'cognitive',message:long?'Continue providing opportunities to practice concepts with guidance. '.repeat(8):'Provide practice opportunities.',priority:'Medium'}],weeksCount:3,weeklyScores:evaluations?[{score:3.1},{score:3.9},{score:4.2}]:[],pastAverage:3.1,recentAverage:3.9,currentWeekAverage:3.9,trend:'Improving'}))}}});});
 return Object.assign(()=>{context();finish();},{fail:(kind:string)=>{failed=kind;},recover:()=>{failed='';}});}
for(const width of [375,1280])for(const dark of [false,true])test(`holistic profile ${width} ${dark?'dark':'light'} known snapshot shell remains real`,async({page})=>{await page.setViewportSize({width,height:1100});const release=await fixture(page,dark);await page.goto(url);await waitForDataRoute(page);await expect(page.getByRole('heading',{name:'Holistic Development Profile',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Whole-Child Snapshot',exact:true})).toBeVisible();await expect(page.getByRole('combobox',{name:'Filter holistic profile by subject',exact:true})).toHaveValue('all');await expect(page.getByText('Cognitive',{exact:true})).toBeVisible();await expect(page.getByText('Per-Subject Breakdown',{exact:true})).toBeVisible();await expect(page.locator('[data-sk-region="holistic-profile-data"]')).toHaveAttribute('data-sk-phase','revealed');await assertNoDataSpinner(page);const verify=await captureFixedOverlay(page,`holistic-profile-${width}-${dark?'dark':'light'}`,['[data-sk-region="holistic-profile-initials"]']);fs.mkdirSync('loading-screenshots',{recursive:true});const prefix=`loading-screenshots/holistic-profile-${width}-${dark?'dark':'light'}`;await page.screenshot({path:prefix+'-skeleton.png',fullPage:true});release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.getByRole('heading',{name:'Ana Cruz',exact:true})).toBeVisible();await expect(page.locator('[data-sk-region="holistic-profile-subject"]')).toHaveCount(2);await verify();await page.screenshot({path:prefix+'-loaded.png',fullPage:true});});
for(const count of [0,1,9])test(`holistic profile preserves ${count} actual subject cards`,async({page})=>{const release=await fixture(page,false,count,count===9);await page.goto(url);await waitForDataRoute(page);release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.locator('[data-sk-region="holistic-profile-subject"]')).toHaveCount(count);});
for(const kind of ['student','profile','terms'])test(`holistic profile retries ${kind} errors`,async({page})=>{const release=await fixture(page,false);release.fail(kind);await page.goto(kind==='terms'?url.replace('?term=1',''):url);await waitForDataRoute(page);release();await expect(page.getByRole('alert')).toBeVisible();await expect(page.locator('[data-sk-primitive]')).toHaveCount(0);release.recover();await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.getByRole('heading',{name:'Ana Cruz',exact:true})).toBeVisible();});
test('holistic profile empty evaluations settle into the original empty state',async({page})=>{const release=await fixture(page,false,1,false,0);await page.goto(url);await waitForDataRoute(page);release();await expect(page.getByText('No evaluations recorded yet.',{exact:true})).toBeVisible();await expect(page.locator('[data-sk-primitive],[role=status]')).toHaveCount(0);});
test('holistic profile subject cards and selector preserve recommendations',async({page})=>{const release=await fixture(page,false);await page.goto(url);await waitForDataRoute(page);release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await page.getByRole('combobox',{name:'Filter holistic profile by subject',exact:true}).selectOption('1');await expect(page.getByText('Recommended actions',{exact:true})).toBeVisible();await expect(page.getByText('Provide practice opportunities.',{exact:true})).toBeVisible();await page.getByRole('combobox',{name:'Filter holistic profile by subject',exact:true}).selectOption('all');await page.locator('[data-sk-region="holistic-profile-subject"]').first().click();await expect(page.getByRole('combobox',{name:'Filter holistic profile by subject',exact:true})).toHaveValue('1');});
for(const dark of [false,true])test(`holistic profile ${dark?'dark':'light'} card text retains actual contrast`,async({page})=>{await fixture(page,dark);await page.goto(url);await waitForDataRoute(page);await expect(page.locator('[data-sk-region="holistic-profile-data"]')).toHaveAttribute('data-sk-phase','revealed');const shape=page.locator('[data-sk-region="holistic-profile-insight-cognitive"] [data-sk-primitive]').first();await checkRenderedContrast(shape,`holistic-profile-${dark?'dark':'light'}`);await checkShimmerPixels(shape,`holistic-profile-${dark?'dark':'light'}`);});
test('holistic profile retains gauge and sparkline shapes',async({page})=>{const release=await fixture(page,false);await page.goto(url);await waitForDataRoute(page);await expect(page.locator('[data-sk-chart="gauge"]')).toHaveCount(4);await expect(page.locator('[data-sk-chart="sparkline"] [data-sk-primitive]')).toHaveCount(2);release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.locator('[data-sk-chart="sparkline"] polyline')).toHaveCount(2);});

test('holistic profile pending selector has valid native option markup',async({page})=>{const errors:string[]=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});const release=await fixture(page,false);await page.goto(url);await waitForDataRoute(page);await expect(page.locator('[data-sk-region="holistic-profile-data"]')).toHaveAttribute('data-sk-phase','revealed');await expect(page.locator('option [data-sk-primitive]')).toHaveCount(0);release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);expect(errors.filter(message=>/cannot be a child|cannot contain|hydration error/.test(message))).toEqual([]);});
