import { waitForDataRoute } from "./fixtures/routeReady";
import {test,expect,type Page} from '@playwright/test';
import fs from 'node:fs';
import {mockDirectory} from './fixtures/directory';
import {assertNoDataSpinner,checkRenderedContrast,checkShimmerPixels} from './design-pixels';
async function fixture(page:Page,dark=false,seen=true,count=3,bonus=false){const context=await mockDirectory(page,'PARENT',dark);context();await page.addInitScript(seen=>{if(seen)localStorage.setItem('ed-intro-seen:1:1','1');else localStorage.removeItem('ed-intro-seen:1:1');},seen);let finish!:()=>void;let gate=new Promise<void>(r=>finish=r);let failed='';const state={levels:bonus?{easy:'completed',medium:'completed',hard:'completed'}:{easy:'available',medium:'locked',hard:'locked'},bonus:{match:false,memory:false},hungerFilled:0,hungerTotal:5,interventionCompleted:false};await page.route('**/api/pet/**',async r=>{await gate;const path=new URL(r.request().url()).pathname;const kind=path.includes('/intervention/')?'state':path.includes('/bonus/')?'bonus':'quiz';await r.fulfill({status:failed===kind?500:200,json:kind==='state'?state:kind==='bonus'?{match:Array.from({length:count},(_,i)=>({id:i,left:'Word '+i,right:'Meaning '+i})),memory:Array.from({length:count},(_,i)=>({id:i,a:'A'+i,b:'B'+i}))}:{practiceSetId:1,title:'Numbers',difficulty:'Easy',gradeLevel:'Grade 1',questions:Array.from({length:count},(_,i)=>({id:i,question_text:'Which number comes next?',choice_a:'One',choice_b:'Two',choice_c:'Three',choice_d:'Four',order_index:i}))}});});return Object.assign(()=>finish(),{hold:()=>gate=new Promise<void>(r=>finish=r),fail:(kind:string)=>failed=kind,recover:()=>failed=''});}
for(const width of [375,1280])for(const dark of [false,true])test(`pet quiz road ${width} ${dark?'dark':'light'} keeps known challenges`,async({page})=>{await page.setViewportSize({width,height:1100});const release=await fixture(page,dark);await page.goto('/parent/students/1/topics/1/quiz');await waitForDataRoute(page);await expect(page.getByText('Choose your challenge!',{exact:true})).toBeVisible();await expect(page.getByText('Easy',{exact:true})).toBeVisible();const region=page.locator('[data-sk-region="pet-quiz-content"]');await expect(region).toHaveAttribute('data-sk-phase','revealed');await assertNoDataSpinner(page);fs.mkdirSync('loading-screenshots',{recursive:true});const prefix=`loading-screenshots/parent-pet-quiz-${width}-${dark?'dark':'light'}`;await page.screenshot({path:prefix+'-skeleton.png',fullPage:true});release();await expect(region).toHaveAttribute('data-sk-phase','settled');await expect(page.locator('[data-sk-primitive]')).toHaveCount(0);await expect(page.getByRole('button',{name:'Easy level, available',exact:true})).toBeEnabled();await page.screenshot({path:prefix+'-loaded.png',fullPage:true});});
test('pet intro keeps its known story visible while access loads',async({page})=>{const release=await fixture(page,false,false);await page.goto('/parent/students/1/topics/1/quiz');await waitForDataRoute(page);await expect(page.getByText("ED's Story",{exact:true})).toBeVisible();await expect(page.locator('[data-sk-region="pet-quiz-content"]')).toHaveAttribute('aria-busy','true');release();await expect(page.locator('[data-sk-region="pet-quiz-content"]')).toHaveAttribute('data-sk-phase','settled');});
test('pet quiz state error clears shapes and retries',async({page})=>{const release=await fixture(page);release.fail('state');await page.goto('/parent/students/1/topics/1/quiz');await waitForDataRoute(page);release();await expect(page.getByRole('alert')).toBeVisible();await expect(page.locator('[data-sk-primitive]')).toHaveCount(0);release.recover();await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByRole('button',{name:'Easy level, available',exact:true})).toBeEnabled();await expect(page.getByRole('alert')).toHaveCount(0);});
for(const width of [375,1280])for(const dark of [false,true])test(`pet quiz question ${width} ${dark?'dark':'light'} reserves real choices`,async({page})=>{await page.setViewportSize({width,height:1100});const release=await fixture(page,dark);await page.goto('/parent/students/1/topics/1/quiz');await waitForDataRoute(page);release();const region=page.locator('[data-sk-region="pet-quiz-content"]');await expect(region).toHaveAttribute('data-sk-phase','settled');release.hold();await page.getByRole('button',{name:'Easy level, available',exact:true}).click();await expect(region).toHaveAttribute('data-sk-phase','revealed');for(const letter of ['A','B','C','D'])await expect(region.getByText(letter,{exact:true})).toBeVisible();await assertNoDataSpinner(page);const prefix=`loading-screenshots/parent-pet-quiz-question-${width}-${dark?'dark':'light'}`;await page.screenshot({path:prefix+'-skeleton.png',fullPage:true});release();await expect(region).toHaveAttribute('data-sk-phase','settled');await expect(page.getByText('Which number comes next?',{exact:true})).toBeVisible();await page.screenshot({path:prefix+'-loaded.png',fullPage:true});});

for(const game of ['Match','Memory'])for(const width of [375,1280])for(const dark of [false,true])test(`pet bonus ${game} ${width} ${dark?'dark':'light'}`,async({page})=>{
 await page.setViewportSize({width,height:1100});const release=await fixture(page,dark,true,3,true);await page.goto('/parent/students/1/topics/1/quiz');await waitForDataRoute(page);release();const region=page.locator('[data-sk-region="pet-quiz-content"]');await expect(region).toHaveAttribute('data-sk-phase','settled');release.hold();await page.getByRole('button',{name:game+' bonus round, available',exact:true}).click();await expect(region).toHaveAttribute('data-sk-phase','revealed');await expect(page.getByText(game==='Match'?'Connect the pairs':'Find the pairs',{exact:true})).toBeVisible();const prefix=`loading-screenshots/parent-pet-quiz-${game}-${width}-${dark?'dark':'light'}`;await page.screenshot({path:prefix+'-skeleton.png',fullPage:true});release();await expect(region).toHaveAttribute('data-sk-phase','settled');await expect(page.locator('[data-sk-primitive], [data-sk-shimmer]')).toHaveCount(0);await page.screenshot({path:prefix+'-loaded.png',fullPage:true});
});
for(const dark of [false,true])test(`pet quiz rendered neutral pixels ${dark}`,async({page})=>{const release=await fixture(page,dark);await page.goto('/parent/students/1/topics/1/quiz');await waitForDataRoute(page);release();const region=page.locator('[data-sk-region="pet-quiz-content"]');await expect(region).toHaveAttribute('data-sk-phase','settled');release.hold();await page.getByRole('button',{name:'Easy level, available',exact:true}).click();await expect(region).toHaveAttribute('data-sk-phase','revealed');const shape=region.locator('[data-sk-primitive="text"]').first();await checkRenderedContrast(shape,'pet-quiz-'+dark);await checkShimmerPixels(shape,'pet-quiz-'+dark);release();await expect(region).toHaveAttribute('data-sk-phase','settled');expect(await region.evaluate(el=>el.getAnimations({subtree:true}).filter(a=>/sk-|skeleton|shimmer/i.test((a as CSSAnimation).animationName??'')).length)).toBe(0);});
for(const kind of ['quiz','bonus'])test(`pet ${kind} failure replaces loading and retries`,async({page})=>{const release=await fixture(page,false,true,3,kind==='bonus');await page.goto('/parent/students/1/topics/1/quiz');await waitForDataRoute(page);release();const region=page.locator('[data-sk-region="pet-quiz-content"]');await expect(region).toHaveAttribute('data-sk-phase','settled');release.hold();release.fail(kind);await page.getByRole('button',{name:kind==='bonus'?'Match bonus round, available':'Easy level, available',exact:true}).click();await expect(region).toHaveAttribute('data-sk-phase','revealed');release();await expect(page.getByRole('button',{name:'Retry',exact:true})).toBeVisible();await expect(page.locator('[data-sk-primitive]')).toHaveCount(0);release.recover();await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByText(kind==='bonus'?'Connect the pairs':'Which number comes next?',{exact:true})).toBeVisible();await expect(page.locator('[data-sk-primitive]')).toHaveCount(0);});
