import { waitForDataRoute } from "./fixtures/routeReady";
import {test,expect,type Page} from '@playwright/test';
import {mockDirectory} from './fixtures/directory';
import {assertNoDataSpinner,captureFixedOverlay,checkRenderedContrast,checkShimmerPixels} from './design-pixels';
import fs from 'node:fs';
async function fixture(page:Page,dark=false,count=3,long=false){const context=await mockDirectory(page,'PRINCIPAL',dark);let finish!:()=>void;const gate=new Promise<void>(r=>{finish=r;});let failed='';const grade=long?'Grade 1 Primary School '.repeat(4):'Grade 1';const subject=long?'Mathematics and quantitative reasoning '.repeat(4):'Mathematics';const ranking=Array.from({length:count},(_,i)=>({rank:i+1,grade:grade+(i+1),subject:subject+(i+1),score:87+i,trend:'up'}));await page.route('**/api/principal-dashboard/**',async route=>{await gate;const path=new URL(route.request().url()).pathname.split('/').pop();let data:unknown=[];if(path==='active-term')data={data:{name:'Term 1',termNumber:1}};else if(path==='overview-summary')data={totalTeachers:12,attendance:94,academicPerf:88};else if(path==='getTodaysAttendance')data={present:29,absent:2,concerning:1};else if(path==='getAttendanceByGrade')data=Array.from({length:count},(_,i)=>({gradeLevelId:i+1,grade:grade+(i+1),type:'grade',attendance:90,present:9,absent:1,total:10,hasRecorded:true}));else if(path==='topSubjectPerGrade')data=ranking;else if(path==='subjectRankingByTerm')data={'Term 1':ranking,'Term 2':ranking.slice(0,1),'Term 3':[]};else if(path==='holisticDomain')data={success:true,data:count?['Cognitive','Emotional','Behavioral','Social'].map(domain=>({domain,score:3.7})):[]};else if(path==='performanceByGrade')data={success:true,data:Array.from({length:count},(_,i)=>({grade:grade+(i+1),score:88,sections:[]}))};else if(path==='performanceTrend')data={success:true,data:[{term:'Term 1',performance:88,attendance:94,holisticAverage:74,overall:85},{term:'Term 2',performance:90,attendance:95,holisticAverage:78,overall:89}]};await route.fulfill({status:failed==='dashboard'?500:200,json:failed==='dashboard'?{message:'Dashboard unavailable'}:data});});await page.route('**/api/student/total-student',async route=>{await gate;await route.fulfill({json:{total:31}});});await page.route('**/api/academic-year/getAcademicYear',async route=>{await gate;await route.fulfill({status:failed==='year'?500:200,json:failed==='year'?{message:'Year unavailable'}:{data:{id:1,label:'2026–2027',status:'Active'}}});});return Object.assign(()=>{context();finish();},{fail:(kind:string)=>{failed=kind;},recover:()=>{failed='';}});}
for(const width of [375,1280])for(const dark of [false,true])test(`principal dashboard ${width} ${dark?'dark':'light'} keeps known shell`,async({page})=>{await page.setViewportSize({width,height:1100});const release=await fixture(page,dark);await page.goto('/principal');await waitForDataRoute(page);await expect(page.getByRole('heading',{name:'Welcome, School User!',exact:true})).toBeVisible();await expect(page.getByText('Total Students',{exact:true})).toBeVisible();await expect(page.getByText('Attendance Rate by Grade Level',{exact:true})).toBeVisible();await expect(page.getByText('Target: 95%',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Expand ranking',exact:true})).toBeAttached();await expect(page.locator('[data-sk-region="principal-dashboard-data"]')).toHaveAttribute('data-sk-phase','revealed');await assertNoDataSpinner(page);const verify=await captureFixedOverlay(page,`principal-dashboard-${width}-${dark?'dark':'light'}`,['[data-sk-region="principal-kpi-total-students"]','[data-sk-region="principal-kpi-total-teachers"]','[data-sk-region="principal-kpi-needs-intervention"]']);fs.mkdirSync('loading-screenshots',{recursive:true});const prefix=`loading-screenshots/principal-dashboard-${width}-${dark?'dark':'light'}`;await page.screenshot({path:prefix+'-skeleton.png',fullPage:true});release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.getByText('31',{exact:true})).toBeVisible();await verify();await page.screenshot({path:prefix+'-loaded.png',fullPage:true});});
for(const count of [0,1,9])test(`principal dashboard preserves ${count} actual grades`,async({page})=>{const release=await fixture(page,false,count,count===9);await page.goto('/principal');await waitForDataRoute(page);release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.locator('[data-sk-region="principal-top-subject"]')).toHaveCount(count);if(!count)await expect(page.getByText('Subject performance will appear when grades are available.',{exact:true})).toBeVisible();});
for(const kind of ['dashboard','year'])test(`principal dashboard retries ${kind}`,async({page})=>{const release=await fixture(page,false);release.fail(kind);await page.goto('/principal');await waitForDataRoute(page);release();await expect(page.getByRole('alert')).toBeVisible();release.recover();await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.getByText('2026–2027',{exact:false})).toBeVisible();});
test('principal dashboard ranking controls preserve loaded behavior',async({page})=>{const release=await fixture(page);await page.goto('/principal');await waitForDataRoute(page);release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.getByText('31',{exact:true})).toBeVisible();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await page.getByRole('combobox').first().selectOption('Term 2');await expect(page.locator('[data-sk-region="principal-ranking-row"]')).toHaveCount(1);await page.getByRole('combobox').first().selectOption('Term 3');await expect(page.getByText('There are no subject rankings for this term yet.',{exact:true})).toBeVisible();});

for(const dark of [false,true])test(`principal dashboard ${dark?'dark':'light'} spotlight contrast and pixel shape`,async({page})=>{await fixture(page,dark);await page.goto('/principal');await waitForDataRoute(page);await expect(page.locator('[data-sk-region="principal-dashboard-data"]')).toHaveAttribute('data-sk-phase','revealed');const shape=page.locator('[data-sk-region="principal-kpi-total-students"] [data-sk-primitive]');await checkRenderedContrast(shape,`principal-spotlight-${dark?'dark':'light'}`);await checkShimmerPixels(shape,`principal-spotlight-${dark?'dark':'light'}`);});
test('principal dashboard charts retain bar line and radar shapes',async({page})=>{const release=await fixture(page);await page.goto('/principal');await waitForDataRoute(page);await expect(page.locator('[data-sk-region="principal-dashboard-data"]')).toHaveAttribute('data-sk-phase','revealed');await expect(page.locator('[data-sk-chart="bar"]')).toHaveCount(6);await expect(page.locator('[data-sk-chart="line"]')).toHaveCount(1);await expect(page.locator('[data-sk-chart="radar"]')).toHaveCount(1);for(const type of ['bar','line','radar'])await expect(page.locator(`[data-sk-chart="${type}"] [data-sk-primitive]`).first()).toBeVisible();release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.locator('[data-sk-chart] [data-sk-primitive]')).toHaveCount(0);});

for(const width of [375,1280])for(const dark of [false,true])test(`principal dashboard ${width} ${dark?'dark':'light'} lower sections retain known labels and geometry`,async({page})=>{await page.setViewportSize({width,height:1100});const release=await fixture(page,dark);await page.goto('/principal');await waitForDataRoute(page);await expect(page.locator('[data-sk-region="principal-dashboard-data"]')).toHaveAttribute('data-sk-phase','revealed');const prefix=`loading-screenshots/principal-dashboard-lower-${width}-${dark?'dark':'light'}`;for(const title of ['Subject Performance','Holistic Development Overview','Academic Performance Overview']){const heading=page.getByRole('heading',{name:title,exact:true});await heading.scrollIntoViewIfNeeded();await expect(heading).toBeVisible();await page.screenshot({path:prefix+'-'+title.replaceAll(' ','-')+'-skeleton.png'});}const ranks=page.locator('[data-sk-region="principal-ranking-row"]');await expect(ranks.first().locator('.h-16.w-16')).toBeAttached();const pendingSize=await ranks.first().locator('.h-16.w-16').boundingBox();expect(pendingSize?.width).toBe(64);expect(pendingSize?.height).toBe(64);release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);for(const title of ['Subject Performance','Holistic Development Overview','Academic Performance Overview']){const heading=page.getByRole('heading',{name:title,exact:true});await heading.scrollIntoViewIfNeeded();await page.screenshot({path:prefix+'-'+title.replaceAll(' ','-')+'-loaded.png'});}});

test('principal dashboard pending rankings mask fetched names grades and scores',async({page})=>{await fixture(page);await page.goto('/principal');await waitForDataRoute(page);await expect(page.locator('[data-sk-region="principal-dashboard-data"]')).toHaveAttribute('data-sk-phase','revealed');for(const row of await page.locator('[data-sk-region="principal-ranking-row"]').all()){await expect(row.locator('[data-sk-primitive]')).toHaveCount(8);expect(await row.innerText()).not.toContain('0%');await expect(row.locator('.flex-1.min-w-0 [data-sk-primitive]')).toHaveCount(3);}});

test('principal dashboard preserves the client-known intervention stub before fetch',async({page})=>{await fixture(page);await page.goto('/principal');await waitForDataRoute(page);await expect(page.locator('[data-sk-region="principal-dashboard-data"]')).toHaveAttribute('data-sk-phase','revealed');const value=page.locator('[data-sk-region="principal-kpi-needs-intervention"]');await expect(value).toHaveText('0');await expect(value.locator('[data-sk-primitive]')).toHaveCount(0);});
