import { waitForDataRoute } from "./fixtures/routeReady";
import { refetchGate, measureFastRefetch } from './fixtures/refetch';
import { test, expect, type Page } from '@playwright/test';
import { mockDirectory } from './fixtures/directory';
import { assertNoDataSpinner, captureFixedOverlay, checkRenderedContrast, checkShimmerPixels } from './design-pixels';
import fs from 'node:fs';
const url='/principal/gradebooks/Grade%201?gradeLevelId=1&sectionId=1&gradingPeriodId=1';
async function fixture(page:Page,dark:boolean,count=3,long=false,secondSubmitted=false,termLabel="Term 1"){
 const context=await mockDirectory(page,'PRINCIPAL',dark);let finish!:()=>void;const gate=new Promise<void>(r=>{finish=r;});let fail='';const refetch=refetchGate();
 await page.route('**/api/academic-year/getAcademicYear',async route=>{await gate;await route.fulfill({status:fail==='year'?500:200,json:fail==='year'?{message:'Year unavailable'}:{status:'success',data:{id:1,label:'2026–2027',status:'Active'}}});});
 await page.route('**/api/gradesheets/**',async route=>{await gate;const path=new URL(route.request().url()).pathname;const period=path.endsWith('grading-period');if(!period)await refetch.wait();if(fail===(period?'period':'book')){await route.fulfill({status:500,json:{message:'Grade sheet unavailable'}});return;}
 await route.fulfill({json:period?{success:true,defaultGradingPeriodId:1,data:[{id:1,term_number:1,term_label:termLabel,is_active:true,is_submitted:true},{id:2,term_number:2,term_label:'Term 2',is_active:false,is_submitted:secondSubmitted}]}:{success:true,data:{sectionName:'Maroon',gradeLevel:'Grade 1',subjects:[{subjectSectionId:'1',subjectId:1,subjectName:long?'Mathematics and quantitative reasoning '.repeat(5):'Mathematics',teacherName:'Ana Cruz',submitted:true}],students:Array.from({length:count},(_,index)=>({studentId:String(index+1),firstName:long?'Maria Alexandra Isabella '.repeat(8):'Ana',lastName:'Cruz',middleName:'A',gender:index%2?'F':'M',grades:{'1':{status:'submitted',termGrade:90,average:90,isOwnAdvisory:true}},overallAverage:90}))}}});
 });return Object.assign(()=>{context();finish();},{fail:(kind:string)=>{fail=kind;},recover:()=>{fail='';},holdBook:refetch.hold,releaseBook:refetch.release});
}
for(const width of [375,1280])for(const dark of [false,true])test(`grade sheet ${width} ${dark?'dark':'light'} keeps known controls and headers real`,async({page})=>{
 await page.setViewportSize({width,height:1100});const release=await fixture(page,dark);await page.goto(url);await waitForDataRoute(page);await expect(page.getByRole('heading',{name:'Grade Sheet',exact:true})).toBeVisible();await expect(page.getByPlaceholder('Search student name or ID...')).toBeVisible();await expect(page.getByRole('columnheader',{name:'Student',exact:true})).toBeVisible();await expect(page.getByRole('columnheader',{name:'Overall Average',exact:true})).toBeVisible();await expect(page.locator('[data-sk-region="principal-grade-sheet-table"]')).toHaveAttribute('data-sk-phase','revealed');await assertNoDataSpinner(page);
 const verify=await captureFixedOverlay(page,`principal-grade-sheet-${width}-${dark?'dark':'light'}`,['[data-sk-region="grade-sheet-stat-Total Students"]','[data-sk-region="grade-sheet-stat-Male"]','[data-sk-region="grade-sheet-stat-Female"]']);fs.mkdirSync('loading-screenshots',{recursive:true});const prefix=`loading-screenshots/principal-grade-sheet-${width}-${dark?'dark':'light'}`;await page.screenshot({path:prefix+'-skeleton.png',fullPage:true});release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.locator('[data-sk-region="grade-sheet-student-row"]')).toHaveCount(3);await verify();await page.screenshot({path:prefix+'-loaded.png',fullPage:true});
});
for(const count of [0,1,9])test(`grade sheet preserves ${count} actual student rows`,async({page})=>{const release=await fixture(page,false,count,count===9);await page.goto(url);await waitForDataRoute(page);await expect(page.getByRole('heading',{name:'Grade Sheet',exact:true})).toBeVisible();release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await expect(page.locator('[data-sk-region="grade-sheet-student-row"]')).toHaveCount(count);if(!count)await expect(page.getByText('No students found.',{exact:true})).toBeVisible();});
for(const kind of ['period','book','year'])test(`grade sheet retries ${kind} errors`,async({page})=>{const release=await fixture(page,false);release.fail(kind);await page.goto(url);await waitForDataRoute(page);release();await expect(page.getByRole('alert')).toBeVisible();await expect(page.locator('[data-sk-primitive]')).toHaveCount(0);release.recover();await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.locator('[data-sk-region="grade-sheet-student-row"]')).toHaveCount(3);});
test('default term lookup keeps the grade sheet shell visible and then selects the server default',async({page})=>{const release=await fixture(page,false);await page.goto(url.replace('&gradingPeriodId=1',''));await waitForDataRoute(page);await expect(page.getByRole('heading',{name:'Grade Sheet',exact:true})).toBeVisible();await expect(page.getByPlaceholder('Search student name or ID...')).toBeVisible();release();await expect(page.getByRole('combobox',{name:'Select grading term',exact:true})).toHaveValue('1');await expect(page.locator('[data-sk-region="grade-sheet-student-row"]')).toHaveCount(3);});
test('unsubmitted term keeps the original unavailable modal and selected term',async({page})=>{const release=await fixture(page,false);await page.goto(url);await waitForDataRoute(page);release();await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);await page.getByRole('combobox',{name:'Select grading term',exact:true}).selectOption('2');await expect(page.getByRole('heading',{name:'Grades Unavailable',exact:true})).toBeVisible();await expect(page.getByRole('combobox',{name:'Select grading term',exact:true})).toHaveValue('1');});
test('grade sheet native columns vary with actual returned content',async({page})=>{const widths:number[][]=[];for(const long of [false,true]){const release=await fixture(page,false,3,long);await page.goto(url);await waitForDataRoute(page);release();await expect(page.locator('[data-sk-region="grade-sheet-student-row"]')).toHaveCount(3);await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);widths.push(await page.locator('thead th').evaluateAll(elements=>elements.map(element=>element.getBoundingClientRect().width)));await page.unroute('**/api/**');await page.unroute('**/api/gradesheets/**');await page.unroute('**/api/academic-year/getAcademicYear');}expect(widths[0].some((width,index)=>Math.abs(width-widths[1][index])>1)).toBe(true);});
for(const dark of [false,true])test(`grade sheet ${dark?'dark':'light'} actual table surface pixels`,async({page})=>{await fixture(page,dark);await page.goto(url);await waitForDataRoute(page);await expect(page.locator('[data-sk-region="principal-grade-sheet-table"]')).toHaveAttribute('data-sk-phase','revealed');const shape=page.locator('[data-sk-region="grade-sheet-student-name"] [data-sk-primitive]').first();await checkRenderedContrast(shape,`grade-sheet-${dark?'dark':'light'}`);await checkShimmerPixels(shape,`grade-sheet-${dark?'dark':'light'}`);});
test('grade sheet repeat view reuses measured native columns and slow refetch retains rows',async({page})=>{
 const release=await fixture(page,false,3,true,true);await page.goto(url);await waitForDataRoute(page);release();await expect(page.locator('[data-sk-region="grade-sheet-student-row"]')).toHaveCount(3);await expect(page.locator('.sk-region[aria-busy="true"]')).toHaveCount(0);const original=await page.locator('thead th').evaluateAll(elements=>elements.map(element=>element.getBoundingClientRect().width));
 for(const target of ['2','1']){release.holdBook();await page.getByRole('combobox',{name:'Select grading term',exact:true}).selectOption(target);const region=page.locator('[data-sk-region="principal-grade-sheet-table"]');await expect(region).toHaveAttribute('data-sk-phase','dimmed');await expect(page.locator('[data-sk-stale]')).toHaveCSS('opacity','0.6');await expect(page.locator('[data-sk-stale] [data-sk-region="grade-sheet-student-row"]')).toHaveCount(3);await assertNoDataSpinner(page);await expect(region).toHaveAttribute('data-sk-phase','revealed');if(target==='1'){const pending=await page.locator('thead th').evaluateAll(elements=>elements.map(element=>element.getBoundingClientRect().width));expect(pending).toHaveLength(original.length);pending.forEach((width,index)=>expect(Math.abs(width-original[index])).toBeLessThanOrEqual(2));}release.releaseBook();await expect(region).toHaveAttribute('data-sk-phase','settled');}
});

for(const dark of [false,true])test(`grade sheet ${dark?'dark':'light'} term value has a measurable placeholder`,async({page})=>{
 await fixture(page,dark);await page.goto(url);await waitForDataRoute(page);const region=page.locator('[data-sk-region="grade-sheet-term"]');await expect(region).toHaveAttribute('data-sk-phase','revealed');const shape=region.locator('[data-sk-primitive]');const box=await shape.boundingBox();expect(box?.width??0).toBeGreaterThan(15);await checkRenderedContrast(shape,`grade-sheet-term-${dark?'dark':'light'}`);await checkShimmerPixels(shape,`grade-sheet-term-${dark?'dark':'light'}`);
});

test('grade sheet fast term refetch never dims or reveals placeholders',async({page})=>{
 const release=await fixture(page,false,3,false,true);await page.goto(url);await waitForDataRoute(page);release();const region=page.locator('[data-sk-region="principal-grade-sheet-table"]');await expect(region).toHaveAttribute('data-sk-phase','settled');
 await region.evaluate(element=>{const phases:string[]=[];(window as unknown as {gradeSheetPhases:string[]}).gradeSheetPhases=phases;new MutationObserver(()=>{phases.push(element.getAttribute('data-sk-phase')??'');}).observe(element,{attributes:true,attributeFilter:['data-sk-phase']});});
 const verifyFast=await measureFastRefetch(page,'gradesheets/');release.holdBook(true);await page.getByRole('combobox',{name:'Select grading term',exact:true}).selectOption('2');await verifyFast();await expect(region).toHaveAttribute('data-sk-phase','settled');const phases=await page.evaluate(()=>(window as unknown as {gradeSheetPhases:string[]}).gradeSheetPhases);expect(phases).toContain('waiting');expect(phases).not.toContain('dimmed');expect(phases).not.toContain('revealed');await expect(page.locator('[data-sk-region="grade-sheet-student-row"]')).toHaveCount(3);await assertNoDataSpinner(page);
});
test('intrinsic term selector stays variable and its loaded width follows actual labels',async({page})=>{
 const widths:number[]=[];for(const label of ['Term 1','First academic grading period']){const release=await fixture(page,false,3,false,false,label);await page.goto(url);await waitForDataRoute(page);const region=page.locator('[data-sk-region="grade-sheet-term"]');await expect(region).toHaveAttribute('data-sk-variable','');release();await expect(region).toHaveAttribute('data-sk-phase','settled');const select=page.getByRole('combobox',{name:'Select grading term',exact:true});widths.push((await select.boundingBox())!.width);expect(await select.evaluate(element=>(element as HTMLElement).style.minWidth)).toBe('');await page.unroute('**/api/**');await page.unroute('**/api/gradesheets/**');await page.unroute('**/api/academic-year/getAcademicYear');}expect(widths[1]-widths[0]).toBeGreaterThan(10);
});


